[package]
name = "user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
proto = { path = "../../common/proto", features = ["user_server", "core_cient"] }
errors = { path = "../../common/errors", features = ["password", "jwt", "grpc"] }
database = { path = "../../common/database", features = ["user"] }
validation = { path = "../../common/validation" }

jsonwebtoken = "8.0.1"
pbkdf2 = "0.10.1"
serde = { version = "1.0.136", features = ["derive"] }

[profile.release]
strip = "symbols"