version: "3.9"
services:
  web:
    image: suxiaoshao/web:latest
    ports:
      - "80:80"
    restart: always
    container_name: web
  graphql:
    image: suxiaoshao/graphql:latest
    restart: always
    container_name: graphql
  auth:
    image: suxiaoshao/auth:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: auth
  user:
    image: suxiaoshao/user:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    container_name: user
  core:
    image: suxiaoshao/core:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
    container_name: core
  open:
    image: suxiaoshao/open:latest
    restart: always
    container_name: open
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    container_name: mongo
    volumes:
      - mongodb:/data/db
  postgres:
    image: suxiaoshao/postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: postgres
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
volumes:
  mongodb:
    name: mongodb
  postgres:
    name: postgres
