[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6.2"
jsonwebtoken = "7.2.0"
sqlx = { version = "0.5.9", features = [ "runtime-tokio-rustls" ] }
pbkdf2 = "0.10.0"
async-graphql = "3.0.18"
