[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
futures = "0.3.21"
mime_guess = "2.0.4"
mongodb = "2.1.0"
mongodb-gridfs = "0.2.2"
blake3 = "1.3.1"

proto = { path = "../../common/proto", features = ["core_server", "user"] }
errors = { path = "../../common/errors", features = ["mongo", "grpc"] }
database = { path = "../../common/database", features = ["core"] }
validation = { path = "../../common/validation", features = [] }

[dev-dependencies]
proto = { path = "../../common/proto", features = ["core_client"] }
