[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
futures = "0.3.19"
proto={path="../../common/proto",features=["core","user"]}
utils={path="../../common/utils",features=["mongo","sql","recursion","future"]}
