[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.1", features = ["macros", "rt-multi-thread"] }
async-graphql = "3.0.38"
axum = { version = "0.5.4", features = ["headers"] }
async-graphql-axum = "3.0.38"
proto = { path = "../../common/proto", features = ["core_client", "user_client", "graphql"] }
tower-http = { version = "0.3.2", features = ["cors"] }
futures = "0.3.21"
anyhow = "1.0.57"
