[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
async-graphql = "3.0.27"
axum = { version = "0.4.4", features = ["headers"] }
async-graphql-axum = "3.0.27"
proto={path="../../common/proto",features=["core","auth","user"]}
utils={path="../../common/utils",features=["graphql"]}
tower-http = { version = "0.2.1", features = ["cors"] }
futures = "0.3.19"
