[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
async-graphql = "3.0.17"
axum = { version = "0.4.3", features = ["headers"] }
async-graphql-axum = "3.0.17"
proto={path="../../common/proto"}
thiserror = "1.0.30"
tonic = "0.6.2"
