[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
async-graphql = "3.0.21"
axum = { version = "0.4.4", features = ["headers"] }
async-graphql-axum = "3.0.21"
proto={path="../../common/proto"}
utils={path="../../common/utils"}
tower-http = { version = "0.2.0", features = ["cors"] }
