[workspace]

members = [
    "packages/graphql",
    "common/proto",
    "common/errors",
    "common/validation",
    "common/database",
    "packages/user",
    "packages/core",
    "packages/open"
]