query bucketList($data: GetListRequest!) {
  bucketList(data: $data) {
    data {
      name
      createTime
      updateTime
      access
    }
    total
  }
}
query bucketInfo($data: GetBucketRequest!) {
  bucketInfo(data: $data) {
    name
    updateTime
    createTime
    access
  }
}
mutation createBucket($data: CreateBucketRequest!) {
  createBucket(data: $data) {
    name
  }
}
mutation updateBucket($data: UpdateBucketRequest!) {
  updateBucket(data: $data) {
    name
  }
}
mutation deleteBucket($data: DeleteBucketRequest!) {
  deleteBucket(data: $data)
}
