query bucketList($data: GetListRequest!) {
  bucketList(data: $data) {
    data {
      name
      createTime
      updateTime
      access
    }
    total
  }
}
query bucketInfo($data: GetBucketRequest!, $startTime: Int!, $endTime: Int!) {
  bucketInfo(data: $data) {
    name
    createTime
    updateTime
    access
    objectSize
    objectCount
    uploadSize(endTime: $endTime, startTime: $startTime)
    downloadSize(startTime: $startTime, endTime: $endTime)
    requestCount(endTime: $endTime, startTime: $startTime)
    uploadSizeChart(endTime: $endTime, startTime: $startTime) {
      startTime
      endTime
      value
    }
    downloadSizeChart(endTime: $endTime, startTime: $startTime) {
      startTime
      endTime
      value
    }
    requestCountChart(endTime: $endTime, startTime: $startTime) {
      startTime
      endTime
      value
    }
    objectCountChart(endTime: $endTime, startTime: $startTime) {
      time
      value
    }
    objectSizeChart(endTime: $endTime, startTime: $startTime) {
      time
      value
    }
  }
}
mutation createBucket($data: CreateBucketRequest!) {
  createBucket(data: $data) {
    name
  }
}
mutation updateBucket($data: UpdateBucketRequest!) {
  updateBucket(data: $data) {
    name
  }
}
mutation deleteBucket($data: DeleteBucketRequest!) {
  deleteBucket(data: $data)
}
