mutation createFolder($data: CreateFolderRequest!) {
  createFolder(data: $data) {
    path
  }
}
mutation updateFolder($data: UpdateFolderRequest!) {
  updateFolder(data: $data) {
    path
  }
}
mutation deleteFolder($data: DeleteFolderRequest!) {
  deleteFolder(data: $data)
}
query folderList($data: GetFolderListRequest!) {
  folderList(data: $data) {
    total
    data {
      ... on FolderInfo {
        path
        createTime
        updateTime
        bucketName
        access
        fatherPath
        folderName
        __typename
      }
      ... on ObjectInfo {
        path
        filename
        bucketName
        objectAccess: access
        createTime
        updateTime
        size
        __typename
      }
    }
  }
}
query getFolderStatistics($data: GetFolderRequest!) {
  folderInfo(data: $data) {
    folderCount
    objectCount
    objectSize
    folderName
  }
}
