# 获取用户列表
query userList($data: ListRequest!) {
  userList(data: $data) {
    data {
      name
      description
      createTime
      updateTime
    }
    total
  }
}
# 获取用户
query userInfo($data: GetUserRequest!) {
  userInfo(data: $data) {
    name
    description
    createTime
    updateTime
  }
}
mutation userCreate($data: CreateUserRequest!) {
  manageUserCreate(data: $data) {
    name
  }
}
mutation userUpdate($data: UpdateUserRequest!) {
  manageUserUpdate(data: $data) {
    name
  }
}
mutation userDelete($data: DeleteUserRequest!) {
  manageUserDelete(data: $data)
}
