# 获取用户列表
query userList($data: GetListRequest!) {
  userList(data: $data) {
    data {
      name
      description
      createTime
      updateTime
    }
    total
  }
}
# 获取用户
query userInfo($data: GetUserRequest!) {
  userInfo(data: $data) {
    name
    description
    createTime
    updateTime
  }
}

query manageDetail($startTime: Int!, $endTime: Int!) {
  manageDetail {
    objectSize
    userCount
    uploadSize(endTime: $endTime, startTime: $startTime)
    downloadSize(startTime: $startTime, endTime: $endTime)
    requestCount(endTime: $endTime, startTime: $startTime)

    uploadSizeChart(endTime: $endTime, startTime: $startTime) {
      startTime
      endTime
      value
    }
    downloadSizeChart(endTime: $endTime, startTime: $startTime) {
      startTime
      endTime
      value
    }
    requestCountChart(endTime: $endTime, startTime: $startTime) {
      startTime
      endTime
      value
    }
    objectCountChart(endTime: $endTime, startTime: $startTime) {
      time
      value
    }
    objectSizeChart(endTime: $endTime, startTime: $startTime) {
      time
      value
    }
  }
}

mutation userCreate($data: CreateUserRequest!) {
  manageUserCreate(data: $data) {
    name
  }
}
mutation userUpdate($data: UpdateUserRequest!) {
  manageUserUpdate(data: $data) {
    name
  }
}
mutation userDelete($data: DeleteUserRequest!) {
  manageUserDelete(data: $data)
}
