query selfUserInfo($data: GetUserInfoRequest!) {
  selfUserInfo(data: $data) {
    name
    createTime
    updateTime
    description
  }
}
mutation updateInfo($data: UpdateUserInfoRequest!) {
  updateInfo(data: $data) {
    name
  }
}
mutation updatePassword($data: UpdatePasswordRequest!) {
  updatePassword(data: $data)
}
