query selfUserInfo {
  selfUserInfo {
    name
    createTime
    updateTime
    description
  }
}

query userStat($startTime: Int!, $endTime: Int!) {
  selfUserInfo {
    objectSize
    objectCount
    uploadSize(endTime: $endTime, startTime: $startTime)
    downloadSize(startTime: $startTime, endTime: $endTime)
    requestCount(endTime: $endTime, startTime: $startTime)
  }
}

mutation updateInfo($data: UpdateUserInfoRequest!) {
  updateInfo(data: $data) {
    name
  }
}
mutation updatePassword($data: UpdatePasswordRequest!) {
  updatePassword(data: $data)
}
