[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic = "0.6.2"
proto={path="../../common/proto"}
jsonwebtoken = "7.2.0"
serde = { version = "1.0.132", features = ["derive"] }
sqlx = { version = "0.5.9", features = [ "runtime-tokio-rustls","postgres","time" ] }
pbkdf2 = "0.10.0"
utils={path="../../common/utils"}
