[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
proto={path="../../common/proto", features=["auth","user"]}
database={path = "../../common/database"}
validation={path = "../../common/validation", features =["login"]}
