[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
proto={path="../../common/proto", features=["auth","core","user"]}
utils={path="../../common/utils", features=["sql","jwt","password"]}
