kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mini-oss
nodes:
  - role: control-plane
    # port forward 80 on the host to 80 on this node
    extraPortMappings:
      - containerPort: 30002
        hostPort: 30002
        protocol: TCP
