[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5.9", features = [ "runtime-tokio-rustls","postgres","time" ] }
tonic = "0.6.2"
proto={path="../proto"}
utils={path="../utils"}
[dev-dependencies]
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }

