[package]
name = "open"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.4.6", features = ["headers", "json"] }
axum-extra = "0.1.4"
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tonic = "0.6.2"
proto = { path = "../../common/proto", features = ["core_cient", "user"] }
tower-http = { version = "0.2.3", features = ["cors"] }
nom = "7.1.0"
futures = "0.3.21"
time = { version = "0.3.7", features = ["std"] }
urlencoding = "2.1.0"

[profile.release]
strip = "symbols"