[package]
name = "open"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.5.1", features = ["headers", "json"] }

# 中间件
tower-http = { version = "0.2.5", features = ["cors"] }
tower = "0.4.12"
hyper = "0.14.18"
bytes = "1.1.0"
http-body = "0.4.4"
pin-project-lite = "0.2.8"

# axum route
nom = "7.1.1"
urlencoding = "2.1.0"

# 缓存
time = { version = "0.3.9", features = ["std"] }

serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

tonic = "0.7.1"
proto = { path = "../../common/proto", features = ["core_client", "user"] }
futures = "0.3.21"

# request
bson = "2.1.0"
database = { path = "../../common/database", features = ["core"]}
errors = { path = "../../common/errors" }

# 错误
anyhow = "1.0.56"
thiserror = "1.0.30"
