name: user_manage-docker-build
on:
  push:
    branches:
      - main
    paths:
      - docker/user_manage.Dockerfile
      - server/packages/user_manage
      - server/common
      - server/.cargo
      - .github/workflows/user_manage.yaml
      - .github/action/docker-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: suxiaoshao/user_manage:latest
          file: ./docker/user_manage.Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
